:config::config_dir is not available
in Puppet 4.x graylog_collector::config::config_dir is not available,
because it is later used at init.pp.

Error: Could not retrieve catalog from remote server: Error 500 on
SERVER: {"message":"Server Error: Invalid relationship:
File[/var/lib/puppet/concat/_collector.conf/fragments/101_input_webapp_login_log]
{ notify => Exec[concat_/collector.conf] }, because
Exec[concat_/collector.conf] doesn't seem to be in the catalog"

This change is tested with Puppet Server (Puppet 4.6) and Puppet 3.8.x
with future parser enabled